name: Rust

on:
  push:
    branches:
     - docs-v2
    tags:
     - "*"

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r docs/v2/requirements.txt
      - name: Build docs
        run: |
          cd docs/v2
          make html-all
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: html_output
          path: docs/v2/build/html
          include-hidden-files: true

  publish_docs:
    name: Publish docs to GitHub Pages
    needs:
      - build_docs
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: html_output
          path: docs/v2/build/html
      - name: Publish HTML
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/v2/build/html
          target-folder: .
